version: "3"

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - 5431:5431
  web:
    build: webapp/.
  server:
    build: .
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - database
      - web
